# Dockerfile - Ubuntu Noble
# https://github.com/openresty/docker-openresty

ARG RESTY_IMAGE_BASE="ubuntu"
ARG RESTY_IMAGE_TAG="noble"

FROM ${RESTY_IMAGE_BASE}:${RESTY_IMAGE_TAG}

LABEL maintainer="huanggq <huanggq@pukkasoft.cn>"

# Docker Build Arguments
ARG RESTY_IMAGE_BASE="ubuntu"
ARG RESTY_IMAGE_TAG="noble"
ARG RESTY_VERSION="1.27.1.1"
ARG RESTY_LUAROCKS_VERSION="3.11.1"

# http://www.modsecurity.cn/, https://github.com/owasp-modsecurity/
ARG MOD_SECURITY_VERSION="3.0.13"
ARG MOD_SECURITY_URL_BASE="https://github.com/owasp-modsecurity/ModSecurity/releases/download/v${MOD_SECURITY_VERSION}"
ARG MOD_SECURITY_NGINX_VERSION="1.0.3"
ARG MOD_SECURITY_NGINX_URL_BASE="https://github.com/owasp-modsecurity/ModSecurity-nginx/releases/download/v${MOD_SECURITY_NGINX_VERSION}"

# https://github.com/coreruleset/coreruleset/releases
ARG MOD_CORERULESET_VERSION="4.8.0"
ARG MOD_CORERULESET_URL_BASE="https://github.com/coreruleset/coreruleset/releases/download/v${MOD_CORERULESET_VERSION}"

# https://github.com/openresty/openresty-packaging/blob/master/deb/openresty-openssl3/debian/rules
ARG RESTY_OPENSSL_VERSION="3.0.15"
ARG RESTY_OPENSSL_PATCH_VERSION="3.0.15"
ARG RESTY_OPENSSL_URL_BASE="https://github.com/openssl/openssl/releases/download/openssl-${RESTY_OPENSSL_VERSION}"
# LEGACY:  "https://www.openssl.org/source/old/1.1.1"
ARG RESTY_OPENSSL_BUILD_OPTIONS="enable-camellia enable-seed enable-rfc3779 enable-cms enable-md2 enable-rc5 \
        enable-weak-ssl-ciphers enable-ssl3 enable-ssl3-method enable-md2 enable-ktls enable-fips \
        "

# https://github.com/openresty/openresty-packaging/blob/master/deb/openresty-pcre2/debian/rules
ARG RESTY_PCRE_VERSION="10.44"
ARG RESTY_PCRE_SHA256="86b9cb0aa3bcb7994faa88018292bc704cdbb708e785f7c74352ff6ea7d3175b"
ARG RESTY_PCRE_BUILD_OPTIONS="--enable-jit --enable-pcre2grep-jit --disable-bsr-anycrlf --disable-coverage --disable-ebcdic --disable-fuzz-support \
    --disable-jit-sealloc --disable-never-backslash-C --enable-newline-is-lf --enable-pcre2-8 --enable-pcre2-16 --enable-pcre2-32 \
    --enable-pcre2grep-callout --enable-pcre2grep-callout-fork --disable-pcre2grep-libbz2 --disable-pcre2grep-libz --disable-pcre2test-libedit \
    --enable-percent-zt --disable-rebuild-chartables --enable-shared --disable-static --disable-silent-rules --enable-unicode --disable-valgrind \
    "

ARG RESTY_J="2"

# https://github.com/openresty/openresty-packaging/blob/master/deb/openresty/debian/rules
ARG RESTY_CONFIG_OPTIONS="\
    --with-compat \
    --without-http_rds_json_module \
    --without-http_rds_csv_module \
    --without-lua_rds_parser \
    --without-mail_pop3_module \
    --without-mail_imap_module \
    --without-mail_smtp_module \
    --with-http_addition_module \
    --with-http_auth_request_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_geoip_module=dynamic \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_image_filter_module=dynamic \
    --with-http_mp4_module \
    --with-http_random_index_module \
    --with-http_realip_module \
    --with-http_secure_link_module \
    --with-http_slice_module \
    --with-http_ssl_module \
    --with-http_stub_status_module \
    --with-http_sub_module \
    --with-http_v2_module \
    --with-http_v3_module \
    --with-http_xslt_module=dynamic \
    --with-ipv6 \
    --with-mail \
    --with-mail_ssl_module \
    --with-md5-asm \
    --with-sha1-asm \
    --with-stream \
    --with-stream_ssl_module \
    --with-stream_ssl_preread_module \
    --with-threads \
    "
ARG RESTY_CONFIG_OPTIONS_MORE=""
ARG RESTY_LUAJIT_OPTIONS="--with-luajit-xcflags='-DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT'"
ARG RESTY_PCRE_OPTIONS="--with-pcre-jit"
ARG RESTY_HEALTHCHECK_MODULE_OPTIONS="--add-module=/tmp/ngx_healthcheck_module-master"
ARG MOD_SECURITY_NGINX_MODULE_OPTIONS="--add-module=/tmp/modsecurity-nginx-v${MOD_SECURITY_NGINX_VERSION}"

ARG RESTY_ADD_PACKAGE_BUILDDEPS="git"
ARG RESTY_ADD_PACKAGE_RUNDEPS=""
ARG RESTY_EVAL_PRE_CONFIGURE=""
ARG RESTY_EVAL_POST_DOWNLOAD_PRE_CONFIGURE=""
ARG RESTY_EVAL_POST_MAKE=""

# These are not intended to be user-specified
ARG _RESTY_CONFIG_DEPS="--with-pcre \
    --with-cc-opt='-DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/pcre2/include -I/usr/local/openresty/openssl3/include' \
    --with-ld-opt='-L/usr/local/openresty/pcre2/lib -L/usr/local/openresty/openssl3/lib -Wl,-rpath,/usr/local/openresty/pcre2/lib:/usr/local/openresty/openssl3/lib' \
    "

LABEL resty_image_base="${RESTY_IMAGE_BASE}"
LABEL resty_image_tag="${RESTY_IMAGE_TAG}"
LABEL resty_version="${RESTY_VERSION}"
LABEL resty_luarocks_version="${RESTY_LUAROCKS_VERSION}"
LABEL resty_openssl_version="${RESTY_OPENSSL_VERSION}"
LABEL resty_openssl_patch_version="${RESTY_OPENSSL_PATCH_VERSION}"
LABEL resty_openssl_url_base="${RESTY_OPENSSL_URL_BASE}"
LABEL resty_openssl_build_options="${RESTY_OPENSSL_BUILD_OPTIONS}"
LABEL resty_pcre_version="${RESTY_PCRE_VERSION}"
LABEL resty_pcre_build_options="${RESTY_PCRE_BUILD_OPTIONS}"
LABEL resty_pcre_sha256="${RESTY_PCRE_SHA256}"
LABEL resty_config_options="${RESTY_CONFIG_OPTIONS}"
LABEL resty_config_options_more="${RESTY_CONFIG_OPTIONS_MORE}"
LABEL resty_config_deps="${_RESTY_CONFIG_DEPS}"
LABEL resty_add_package_builddeps="${RESTY_ADD_PACKAGE_BUILDDEPS}"
LABEL resty_add_package_rundeps="${RESTY_ADD_PACKAGE_RUNDEPS}"
LABEL resty_eval_pre_configure="${RESTY_EVAL_PRE_CONFIGURE}"
LABEL resty_eval_post_download_pre_configure="${RESTY_EVAL_POST_DOWNLOAD_PRE_CONFIGURE}"
LABEL resty_eval_post_make="${RESTY_EVAL_POST_MAKE}"
LABEL resty_luajit_options="${RESTY_LUAJIT_OPTIONS}"
LABEL resty_pcre_options="${RESTY_PCRE_OPTIONS}"
LABEL resty_healthcheck_module_options="${RESTY_HEALTHCHECK_MODULE_OPTIONS}"

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        gettext-base \
        libgd-dev \
        libgeoip-dev \
        libncurses5-dev \
        libperl-dev \
        libreadline-dev \
        libxslt1-dev \
        make \
        perl \
        unzip \
        wget \
        zlib1g-dev \
        g++ \
        flex \
        bison \
        lua5.4 \
        liblua5.4-dev \
        libcurl4-openssl-dev \
        zlib1g-dev \
        libpcre3-dev \
        libpcre2-dev \
        libxml2-dev \
        ssdeep \
        libtool \
        autoconf \
        automake \
        doxygen \
        libyajl-dev \
        libyajl2 \
        liblmdb-dev \
        libfuzzy-dev \
        pkg-config \
        ${RESTY_ADD_PACKAGE_BUILDDEPS} \
        ${RESTY_ADD_PACKAGE_RUNDEPS} \
    && cd /tmp \
    && curl -fSL "${MOD_SECURITY_URL_BASE}/modsecurity-v${MOD_SECURITY_VERSION}.tar.gz" -o modsecurity-v${MOD_SECURITY_VERSION}.tar.gz \
    && tar -zxf modsecurity-v${MOD_SECURITY_VERSION}.tar.gz \
    && cd modsecurity-v${MOD_SECURITY_VERSION} \
    && ./build.sh \
    && ./configure \
    && make -j${RESTY_J} \
    && make -j${RESTY_J} install \
    && cd /tmp \
    && curl -fSL "${MOD_SECURITY_NGINX_URL_BASE}/modsecurity-nginx-v${MOD_SECURITY_NGINX_VERSION}.tar.gz" -o modsecurity-nginx-v${MOD_SECURITY_NGINX_VERSION}.tar.gz \
    && tar -zxf modsecurity-nginx-v${MOD_SECURITY_NGINX_VERSION}.tar.gz \
    && if [ -n "${RESTY_EVAL_PRE_CONFIGURE}" ]; then eval $(echo ${RESTY_EVAL_PRE_CONFIGURE}); fi \
    && curl -fSL "${RESTY_OPENSSL_URL_BASE}/openssl-${RESTY_OPENSSL_VERSION}.tar.gz" -o openssl-${RESTY_OPENSSL_VERSION}.tar.gz \
    && tar xzf openssl-${RESTY_OPENSSL_VERSION}.tar.gz \
    && cd openssl-${RESTY_OPENSSL_VERSION} \
    && if [ $(echo ${RESTY_OPENSSL_VERSION} | cut -c 1-5) = "3.0.15" ] ; then \
        echo 'patching OpenSSL 3.0.15 for OpenResty' \
        && curl -s https://raw.githubusercontent.com/openresty/openresty/master/patches/openssl-${RESTY_OPENSSL_PATCH_VERSION}-sess_set_get_cb_yield.patch | patch -p1 ; \
    fi \
    && if [ $(echo ${RESTY_OPENSSL_VERSION} | cut -c 1-5) = "1.1.1" ] ; then \
        echo 'patching OpenSSL 1.1.1 for OpenResty' \
        && curl -s https://raw.githubusercontent.com/openresty/openresty/master/patches/openssl-${RESTY_OPENSSL_PATCH_VERSION}-sess_set_get_cb_yield.patch | patch -p1 ; \
    fi \
    && if [ $(echo ${RESTY_OPENSSL_VERSION} | cut -c 1-5) = "1.1.0" ] ; then \
        echo 'patching OpenSSL 1.1.0 for OpenResty' \
        && curl -s https://raw.githubusercontent.com/openresty/openresty/ed328977028c3ec3033bc25873ee360056e247cd/patches/openssl-1.1.0j-parallel_build_fix.patch | patch -p1 \
        && curl -s https://raw.githubusercontent.com/openresty/openresty/master/patches/openssl-${RESTY_OPENSSL_PATCH_VERSION}-sess_set_get_cb_yield.patch | patch -p1 ; \
    fi \
    && ./config \
      shared zlib -g \
      --prefix=/usr/local/openresty/openssl3 \
      --libdir=lib \
      -Wl,-rpath,/usr/local/openresty/openssl3/lib \
      ${RESTY_OPENSSL_BUILD_OPTIONS} \
    && make -j${RESTY_J} \
    && make -j${RESTY_J} install_sw \
    && cd /tmp \
    && curl -fSL "https://github.com/PCRE2Project/pcre2/releases/download/pcre2-${RESTY_PCRE_VERSION}/pcre2-${RESTY_PCRE_VERSION}.tar.gz" -o pcre2-${RESTY_PCRE_VERSION}.tar.gz \
    && echo "${RESTY_PCRE_SHA256}  pcre2-${RESTY_PCRE_VERSION}.tar.gz" | shasum -a 256 --check \
    && tar xzf pcre2-${RESTY_PCRE_VERSION}.tar.gz \
    && cd /tmp/pcre2-${RESTY_PCRE_VERSION} \
    && CFLAGS="-g -O3" ./configure \
        --prefix=/usr/local/openresty/pcre2 \
        --libdir=/usr/local/openresty/pcre2/lib \
        ${RESTY_PCRE_BUILD_OPTIONS} \
    && CFLAGS="-g -O3" make -j${RESTY_J} \
    && CFLAGS="-g -O3" make -j${RESTY_J} install \
    && cd /tmp \
    && curl -fSL https://openresty.org/download/openresty-${RESTY_VERSION}.tar.gz -o openresty-${RESTY_VERSION}.tar.gz \
    && tar xzf openresty-${RESTY_VERSION}.tar.gz \
    && curl -fSL https://github.com/zhouchangxun/ngx_healthcheck_module/archive/refs/heads/master.zip -o ngx_healthcheck_module.zip \
    && unzip ngx_healthcheck_module.zip \
    && cd /tmp/openresty-${RESTY_VERSION}/bundle/nginx-1.27.1 \
    && patch -p1 < /tmp/ngx_healthcheck_module-master/nginx_healthcheck_for_nginx_1.19+.patch \
    && cd /tmp/openresty-${RESTY_VERSION} \
    && sed -ri '/^#define NGINX_VER/s/".*"/"loveyou3000\/"/' bundle/nginx-1.27.1/src/core/nginx.h \
    && sed -ri '/^#define NGINX_VAR/s/".*"/"LOVEYOU"/' bundle/nginx-1.27.1/src/core/nginx.h \
    && sed -ri '/^#define NGINX_VERSION/s/".*"/"2000.01.01"/' bundle/nginx-1.27.1/src/core/nginx.h \
    && sed -i 's#<hr><center>openresty</center>#<hr><center>loveyou3000</center>#' bundle/nginx-1.27.1/src/http/ngx_http_special_response.c \
    && sed -i 's/Server: openresty/Server: loveyou3000/' bundle/nginx-1.27.1/src/http/ngx_http_header_filter_module.c \
    && if [ -n "${RESTY_EVAL_POST_DOWNLOAD_PRE_CONFIGURE}" ]; then eval $(echo ${RESTY_EVAL_POST_DOWNLOAD_PRE_CONFIGURE}); fi \
    && eval ./configure -j${RESTY_J} ${_RESTY_CONFIG_DEPS} ${RESTY_CONFIG_OPTIONS} ${RESTY_CONFIG_OPTIONS_MORE} ${RESTY_LUAJIT_OPTIONS} ${RESTY_PCRE_OPTIONS} ${MOD_SECURITY_NGINX_MODULE_OPTIONS} ${RESTY_HEALTHCHECK_MODULE_OPTIONS} \
    # && eval ./configure -j${RESTY_J} ${_RESTY_CONFIG_DEPS} ${RESTY_CONFIG_OPTIONS} ${RESTY_CONFIG_OPTIONS_MORE} ${RESTY_LUAJIT_OPTIONS} ${RESTY_PCRE_OPTIONS} ${RESTY_HEALTHCHECK_MODULE_OPTIONS} \
    && make -j${RESTY_J} \
    && make -j${RESTY_J} install \
    && cd /tmp \
    && mkdir /usr/local/openresty/nginx/conf/modsecurity \
    && cp -p modsecurity-v${MOD_SECURITY_VERSION}/modsecurity.conf-recommended /usr/local/openresty/nginx/conf/modsecurity/modsecurity.conf \
    && cp -p modsecurity-v${MOD_SECURITY_VERSION}/unicode.mapping /usr/local/openresty/nginx/conf/modsecurity/unicode.mapping \
    && curl -fSL "${MOD_CORERULESET_URL_BASE}/coreruleset-${MOD_CORERULESET_VERSION}-minimal.tar.gz" -o coreruleset-${MOD_CORERULESET_VERSION}-minimal.tar.gz \
    && tar -zxf coreruleset-${MOD_CORERULESET_VERSION}-minimal.tar.gz \
    && if [ -f "coreruleset-${MOD_CORERULESET_VERSION}/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example" ]; then \
        mv "coreruleset-${MOD_CORERULESET_VERSION}/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example" \
        "coreruleset-${MOD_CORERULESET_VERSION}/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf"; \
    fi \
    && if [ -f "coreruleset-${MOD_CORERULESET_VERSION}/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example" ]; then \
        mv "coreruleset-${MOD_CORERULESET_VERSION}/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example" \
        "coreruleset-${MOD_CORERULESET_VERSION}/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf"; \
    fi \
    && cp -p coreruleset-${MOD_CORERULESET_VERSION}/crs-setup.conf.example /usr/local/openresty/nginx/conf/modsecurity/crs-setup.conf \
    && cp -rp coreruleset-${MOD_CORERULESET_VERSION}/rules /usr/local/openresty/nginx/conf/modsecurity/ \
    && sed -i 's/SecRuleEngine DetectionOnly/SecRuleEngine On/' /usr/local/openresty/nginx/conf/modsecurity/modsecurity.conf \
    && echo -e "Include crs-setup.conf\nInclude rules/*.conf" >> /usr/local/openresty/nginx/conf/modsecurity/modsecurity.conf \
    && rm -rf \
        openssl-${RESTY_OPENSSL_VERSION}.tar.gz openssl-${RESTY_OPENSSL_VERSION} \
        pcre2-${RESTY_PCRE_VERSION}.tar.gz pcre2-${RESTY_PCRE_VERSION} \
        openresty-${RESTY_VERSION}.tar.gz openresty-${RESTY_VERSION} \
        modsecurity-v${MOD_SECURITY_VERSION}.tar.gz modsecurity-v${MOD_SECURITY_VERSION} \
        modsecurity-nginx-v${MOD_SECURITY_NGINX_VERSION}.tar.gz modsecurity-nginx-v${MOD_SECURITY_NGINX_VERSION} \
        coreruleset-${MOD_CORERULESET_VERSION}-minimal.tar.gz coreruleset-${MOD_CORERULESET_VERSION} \
    && curl -fSL https://luarocks.github.io/luarocks/releases/luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz -o luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz \
    && tar xzf luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz \
    && cd luarocks-${RESTY_LUAROCKS_VERSION} \
    && ./configure \
        --prefix=/usr/local/openresty/luajit \
        --with-lua=/usr/local/openresty/luajit \
        --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1 \
    && make build \
    && make install \
    && cd /tmp \
    && if [ -n "${RESTY_EVAL_POST_MAKE}" ]; then eval $(echo ${RESTY_EVAL_POST_MAKE}); fi \
    && rm -rf luarocks-${RESTY_LUAROCKS_VERSION} luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz ngx_healthcheck_module-master ngx_healthcheck_module.zip \
    && if [ -n "${RESTY_ADD_PACKAGE_BUILDDEPS}" ]; then DEBIAN_FRONTEND=noninteractive apt-get remove -y --purge ${RESTY_ADD_PACKAGE_BUILDDEPS} ; fi \
    && DEBIAN_FRONTEND=noninteractive apt-get autoremove -y \
    && mkdir -p /var/run/openresty /etc/nginx/conf.d/ \
    && ln -sf /dev/stdout /usr/local/openresty/nginx/logs/access.log \
    && ln -sf /dev/stderr /usr/local/openresty/nginx/logs/error.log

# Add additional binaries into PATH for convenience
ENV PATH=$PATH:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin

# Add LuaRocks paths
# If OpenResty changes, these may need updating:
#    /usr/local/openresty/bin/resty -e 'print(package.path)'
#    /usr/local/openresty/bin/resty -e 'print(package.cpath)'
ENV LUA_PATH="/usr/local/openresty/site/lualib/?.ljbc;/usr/local/openresty/site/lualib/?/init.ljbc;/usr/local/openresty/lualib/?.ljbc;/usr/local/openresty/lualib/?/init.ljbc;/usr/local/openresty/site/lualib/?.lua;/usr/local/openresty/site/lualib/?/init.lua;/usr/local/openresty/lualib/?.lua;/usr/local/openresty/lualib/?/init.lua;./?.lua;/usr/local/openresty/luajit/share/luajit-2.1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/openresty/luajit/share/lua/5.1/?.lua;/usr/local/openresty/luajit/share/lua/5.1/?/init.lua"

ENV LUA_CPATH="/usr/local/openresty/site/lualib/?.so;/usr/local/openresty/lualib/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/openresty/luajit/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so;/usr/local/openresty/luajit/lib/lua/5.1/?.so"

# Copy nginx configuration files
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY nginx.vh.default.conf /etc/nginx/conf.d/default.conf

CMD ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]

# Use SIGQUIT instead of default SIGTERM to cleanly drain requests
# See https://github.com/openresty/docker-openresty/blob/master/README.md#tips--pitfalls
STOPSIGNAL SIGQUIT
